/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package formularios.componentes;

import jiconfont.IconCode;
import jiconfont.swing.IconFontSwing;
import utiles.Constantes;

/**
 *
 * @author Alex
 */
public class MenuItem extends javax.swing.JPanel {
    private IconCode icono;
    private String nombre;
    
    /** Creates new form MenuItem */
    public MenuItem(IconCode ico, String nomb) {
        this.icono = ico;
        this.nombre = nomb;
        initComponents();
        initMenu();
        setName(nomb);
     }
    
    private void initMenu(){
        this.setBackground(Constantes.COLOR_PRIMARIO);
        lblIcono.setIcon(IconFontSwing.buildIcon(icono, 30, Constantes.COLOR_BLANCO));
        lblNombre.setForeground(Constantes.COLOR_BLANCO);
        lblNombre.setText(nombre);
    }
    
    /*Función para cuando este menú esté seleccionado*/
    public void setColor(){
        this.setBackground(Constantes.COLOR_BLANCO);
        lblIcono.setIcon(IconFontSwing.buildIcon(icono, 30, Constantes.COLOR_PRIMARIO));
        lblNombre.setForeground(Constantes.COLOR_PRIMARIO);
    }
    
    
    public void resetColor(){
        this.setBackground(Constantes.COLOR_PRIMARIO);
        lblIcono.setIcon(IconFontSwing.buildIcon(icono, 30, Constantes.COLOR_BLANCO));
        lblNombre.setForeground(Constantes.COLOR_BLANCO);
    }
    
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblIcono = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();

        setBackground(Constantes.COLOR_PRIMARIO);
        setMaximumSize(new java.awt.Dimension(2147483647, 60));
        setPreferredSize(new java.awt.Dimension(200, 60));
        setLayout(new java.awt.BorderLayout());

        lblIcono.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIcono.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        lblIcono.setPreferredSize(new java.awt.Dimension(60, 0));
        add(lblIcono, java.awt.BorderLayout.LINE_START);

        lblNombre.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblNombre.setForeground(Constantes.COLOR_PRIMARIO);
        add(lblNombre, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblIcono;
    private javax.swing.JLabel lblNombre;
    // End of variables declaration//GEN-END:variables

}
